name: dadstamps
on: [push]
jobs:
  deploy-cloud-functions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: get_categories
        runtime: nodejs10
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
