name: dadstamps
on: [push]
jobs:
  deploy-cloud-functions:
    runs-on: ubuntu-latest
    steps:
      id: deploy-function
      - uses: google-github-actions/deploy-cloud-functions@v0.1.0
      with:
        name: get_categories
        runtime: nodejs10
        project: ${{ secrets.GCLOUD_PROJECT_ID }}
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
